services:
  # MongoDB Service
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - mern-network

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
    - ./backend/.env
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - Client_ID=${Client_ID}
      - Client_Secret=${Client_Secret}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
      - RENDER_EXTERNAL_URL=${RENDER_EXTERNAL_URL}
    depends_on:
      - mongodb
    networks:
      - mern-network
    restart: unless-stopped

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://54-234-229-97.nip.io:3000
    depends_on:
      - backend
    networks:
      - mern-network
    restart: unless-stopped

# Networks and Volumes
volumes:
  mongodb_data:

networks:
  mern-network:
    driver: bridge